sil11\VitrineBundle\Entity\Order:
    type: entity
    table: order_list
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date: 
            type: date
        submited:
            type: string
            lenght: 3
    manyToOne:
        customer:
            targetEntity: Customer
            inversedBy: orders
            joinColumn:
                name: customer_id
                referencedColumnName: id
