sil11\VitrineBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        item: 
            type: string
            length: 100
        reference:
            type: smallint
            lenght: 5
        price:
            type: decimal
            scale: 2
        description:
            type: text
        quantity:
            type: integer
        file:
          type : string
          maxSize: 5000000
          nullable: true
          maxSizeMessage: 'Votre image ne doit pas dépassée 5Mo'

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id   
    oneToMany:
        orders:
            targetEntity: Order_line
            mappedBy: order
    oneToMany:
        products:
            targetEntity: Order_line
            mappedBy: product