# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

  app.picture_uploader:
    class: AppBundle\FileUploader
    arguments: ['%pictures_directory%']